In [15]:
import numpy as np

In [16]:
"""
Step 1: Import libraries and prepare data
"""
# Features (hours studied)
X = np.array([1, 2, 3, 4, 5])
print('X: ',X)

# Target (exam score)
y = np.array([1, 3, 3, 2, 5])
print('y: ',y)

X:  [1 2 3 4 5]
y:  [1 3 3 2 5]


In [17]:
"""
Step 2: Add bias term (intercept)
To include the intercept in the same formula as the weights, we add a column of 1s to X:
y = Xw
"""
# Reshape X into a column vector
X = X.reshape(-1, 1)
print('reshaped X: \n',X)

# Add a column of ones for the intercept
X_b = np.c_[np.ones((X.shape[0], 1)), X]  # shape: (n_samples, 2)
print('X_b with bias term: \n',X_b)

reshaped X: 
 [[1]
 [2]
 [3]
 [4]
 [5]]
X_b with bias term: 
 [[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]]


In [21]:
"""
Step 3: Compute weights with Normal Equation

The Normal Equation gives the closed-form solution:
w = (X^T * X)^(-1) * X^T * y

This vector w will contain [intercept, slope].
"""
# Normal Equation
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

intercept, slope = theta_best
print("Intercept (bias):", intercept)
print("Coefficient (weight):", slope)

Intercept (bias): 0.7000000000000026
Coefficient (weight): 0.7000000000000005


In [19]:
"""
Step 4: Make predictions

Now we can predict exam scores:
"""
# Predict for new data
X_new = np.array([[0], [6]])  # 0h and 6h studied
X_new_b = np.c_[np.ones((X_new.shape[0], 1)), X_new]

print("New data (hours studied): \n",X_new)
print("New data with bias term: \n",X_new_b)

y_pred = X_new_b.dot(theta_best)
print("Predictions:", y_pred)

New data (hours studied): 
 [[0]
 [6]]
New data with bias term: 
 [[1. 0.]
 [1. 6.]]
Predictions: [-77. 259.]
