## Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

#### Second definition
NumPy (Numerical Python) is the core library for numerical computing in Python. It provides high-performance, multidimensional arrays and tools to work with them efficiently.

> Installation <br>
`!pip install numpy`

In [2]:
# Importing NumPy
import numpy as np

In [7]:
# Creating arrays from python list
a = np.array([1, 2, 3])             # 1D array
b = np.array([[1, 2], [3, 4]])      # 2D array

In [8]:
# Built-in methods
np.zeros((2, 3))     # 2x3 array of zeros
np.ones((3, 3))      # 3x3 array of ones
np.full((2, 2), 7)   # 2x2 array filled with 7
np.eye(3)            # 3x3 identity matrix
np.random.rand(2, 3) # 2x3 array with random values [0,1)
np.arange(0, 10, 2)  # [0 2 4 6 8]
np.linspace(0, 1, 5) # 5 evenly spaced values between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
# Array properties
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.shape       # (2, 3)
arr.ndim        # 2 (dimensions)
arr.dtype       # data type (e.g., int64)
arr.size        # total elements
arr.itemsize    # bytes per element

8

In [ ]:
# Indexing and Slicing
arr[0, 1]        # value at row 0, column 1
arr[0]           # first row
arr[:, 1]        # second column
arr[1:, :2]      # subarray: rows from 1, columns up to 2

In [ ]:
# Math Operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b
a * b
a ** 2
np.exp(a)
np.sqrt(a)

In [ ]:
# Aggregations
arr.sum()
arr.mean()
arr.std()
arr.min()
arr.max()
arr.argmax()     # index of max value
arr.cumsum()     # cumulative sum

In [ ]:
# Broadcasting
a = np.array([1, 2, 3])
b = np.array([[1], [2]])
a + b  # result: 2x3 array

In [ ]:
# Array Manipulation
arr = np.array([[1, 2], [3, 4], [5, 6]])

arr.reshape(2, 3)        # reshape
arr.T                    # transpose
arr.flatten()            # convert to 1D
np.concatenate([a, b])   # merge arrays

In [ ]:
# Boolean Indexing (Filtering)
arr = np.array([1, 2, 3, 4, 5])
arr[arr > 2]           # Output: [3 4 5]
arr[arr % 2 == 0]      # Even numbers: [2 4]

# With np.where
np.where(arr > 3)      # Output: (array([3, 4]),)
arr[np.where(arr > 3)] # Output: [4 5]

# Combine Multiple Conditions
arr[(arr > 2) & (arr < 5)]     # Output: [3 4]
arr[(arr < 2) | (arr > 4)]     # Output: [1 5]
# ⚠️ Use &, |, and ~ instead of and, or, not. Wrap conditions in parentheses.

# Negation
arr[~(arr > 2)]         # Output: [1 2]

# Filtering 2D Arrays
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix[matrix > 5]      # Output: [6 7 8 9]

# Set values conditionally
arr[arr < 3] = 0        # Replace values < 3 with 0
# Result: [0 0 3 4 5]

# Using boolean arrays directly
mask = np.array([True, False, True, False, True])
arr[mask]               # Output: [1 3 5]

In [ ]:
# Matrix & Linear Algebra Operations in NumPy
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[2, 0],
              [1, 3]])

# 1. Matrix Multiplication (Dot Product)
C = A @ B           # or: np.dot(A, B)
print(C)  # Output: [[ 4  6]
"""
Math equivalent:
A = [1,2]
    [3,4]

B = [2,0]
    [1,3]

A x B = [(1 x 2 + 2 x 1), (1 x 0 + 2 x 3)], [(3 x 2 + 4 x 1), (3 x 0 + 4 x 3)]
= [4,6], [10,12]
"""

[[ 4  6]
 [10 12]]


'\nMath equivalent:\nA = [1,2], [3,4]\nB = [2,0], [1,3]\n\nA x B = [(1 x 2 + 2 x 1), (1 x 0 + 2 x 3)], [(3 x 2 + 4 x 1), (3 x 0 + 4 x 3)]\n= [4,6], [10,12]\n'

In [6]:
print(234 / 26)

9.0


In [3]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [4]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
# identity matrix
np.eye(3)  # 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size (number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size (bytes per element):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (bytes per element): 8
